### ISSUE TITLE
Broker property to indicate active/passive cluster

### ISSUE THREAD

**Issue by naveen8384** [confluentinc/kafka-images#113]
Hello,
We have two clusters one is EAST and another is WEST. EAST will be primary and WEST will be DR, if EAST cluster went down WEST will be primary.  Now the issue is how can consumer know which cluster is primary? Is there any property to indicate primary cluster or any another way to handle DR in kafka?

**Comment by andrewegel** [comment]
This project is for the docker images that "wrap" or contain the piece of software we know as apache/kafka. Docker images don't have this integration or concept about the internal states of a cluster. Thats why your question is better suited for the apache-kafka maintainers directly: https://kafka.apache.org/contact.html
