### ISSUE TITLE
Security vulnerability in kafka confluentinc/cp-kafka:5.5.0 version via trivy scanning tool

### ISSUE THREAD

**Issue by omthakare** [confluentinc/kafka-images#123]
[confluentinc-cp-kafka%3A5.5.0.txt](https://github.com/confluentinc/kafka-images/files/7562413/confluentinc-cp-kafka.3A5.5.0.txt)

We are trying to test the security vulnerability using aquasec-trivy scanning tool. we found lot of vulnerability and attached vulnerability report. could you please provide us solution for fixing out this high vulnerability issues. Thank You

**Comment by omthakare** [comment]
Hi Team,

Do you have any update or resolution for above issue. could you please update on this. Thank You.

**Comment by andrewegel** [comment]
You'll need to do two things:
* Use the -ubi8 suffixed images, which are based on RHEL8, and not an EoL OS (Debian8). Thats going to resolve a majority of your issues.
* Use the "latest" 5.5.x docker image. That will be `5.5.6-10-ubi8` today, and then a `5.5.7-1-ubi8` later on this month when 5.5.7 is released.
