### ISSUE TITLE
Kafka Not Starting up in EC2

### ISSUE THREAD

**Issue by PalAditya** [confluentinc/kafka-images#124]
As you can see, I have used the **cp-zookeeper:latest** and **cp-kafka:latest** images here. However, while zookeeper starts up fine, the Kafka exits sometime without **any** error logs, so I don't even know where to start looking.

```shell
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                    PORTS                          NAMES
1c66dfef70e9   confluentinc/cp-kafka:latest     "/etc/confluent/dock…"   39 seconds ago   Up 38 seconds             9092/tcp                       kafka
cccda3c5751a   confluentinc/cp-zookeeper        "/etc/confluent/dock…"   12 minutes ago   Up 12 minutes             2181/tcp, 2888/tcp, 3888/tcp   zookeeper
99b6ca23ca42   amazon/amazon-ecs-agent:latest   "/agent"                 33 minutes ago   Up 33 minutes (healthy)                                  ecs-agent
[root@ip-10-0-151-119 kafka-data]# docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                    PORTS                          NAMES
cccda3c5751a   confluentinc/cp-zookeeper        "/etc/confluent/dock…"   12 minutes ago   Up 12 minutes             2181/tcp, 2888/tcp, 3888/tcp   zookeeper
99b6ca23ca42   amazon/amazon-ecs-agent:latest   "/agent"                 33 minutes ago   Up 33 minutes (healthy)                                  ecs-agent
[root@ip-10-0-151-119 kafka-data]# docker logs 1c66dfef70e9
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Configuring ...
===> Running preflight checks ...
===> Check if /var/lib/kafka/data is writable ...
===> Check if Zookeeper is healthy ...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/java/cp-base-new/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/cp-base-new/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (io.confluent.admin.utils.cli.ZookeeperReadyCommand).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[root@ip-10-0-151-119 kafka-data]# ^C
```

Can you please suggest what I can do to debug this further? The lack of any error message is very confusing

**Comment by andrewegel** [comment]
This issue (The fix for the issue) is masking the reason why the ZookeeperReadyCommand is failing: https://github.com/confluentinc/common-docker/pull/170 - Its a WIP and once merged, it'll go out with 7.0.2 sometime in Q1 2022. This isn't a fix for your issue, its only going to print what the real issue is you're encountering. 

To get around this until the change can get into your hands: Mount a default log4j.properties config file (such as [1]) into the container, then pass to `docker run --environment KAFKA_OPTS="-Dlog4j.configuration=file:///path/to/mounted/log4j.properties"` - That will init log4j and start printing what the real issue is.

[1] https://github.com/confluentinc/common-docker/blob/master/docker-utils/main/resources/log4j.properties

**Comment by PalAditya** [comment]
Sorry for not coming back to this - the suggestion worked and I was able to check the logs and it was indeed a misconfiguration made by me. Thus, closing the issue.

**Comment by LiGuoshen** [comment]
> Sorry for not coming back to this - the suggestion worked and I was able to check the logs and it was indeed a misconfiguration made by me. Thus, closing the issue.

Hi could you please tell me how to fixed that? I face the same issue right now!!!
