### ISSUE TITLE
JMS Connector source task failing if it stays idle for longer, but works after removing and creating the connector again

### ISSUE THREAD

**Issue by ceecer1** [confluentinc/kafka-images#150]
**For below configuration:**

FROM confluentinc/cp-kafka-connect-base:6.2.1
RUN   confluent-hub install --no-prompt confluentinc/kafka-connect-jms:11.0.11

**Logs here:**

org.apache.kafka.connect.errors.ConnectException: Failed on attempt 1 of 2147483647 to receive JMS message: oracle.jms.AQjmsException: JMS-120: Dequeue failed\n\tat io.confluent.connect.utils.retry.RetryPolicy.callWith(RetryPolicy.java:423)\n\tat io.confluent.connect.utils.retry.RetryPolicy.call(RetryPolicy.java:337)\n\tat io.confluent.connect.jms.core.source.BaseJmsSourceTask.poll(BaseJmsSourceTask.java:289)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:296)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:253)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: org.apache.kafka.connect.errors.ConnectException: oracle.jms.AQjmsException: JMS-120: Dequeue failed\n\tat io.confluent.connect.jms.core.source.BaseJmsSourceTask.receive(BaseJmsSourceTask.java:201)\n\tat io.confluent.connect.jms.core.source.BaseJmsSourceTask.lambda$poll$0(BaseJmsSourceTask.java:291)\n\tat io.confluent.connect.utils.retry.RetryPolicy.lambda$call$1(RetryPolicy.java:337)\n\tat io.confluent.connect.utils.retry.RetryPolicy.callWith(RetryPolicy.java:417)\n\t... 11 more\nCaused by: oracle.jms.AQjmsException: JMS-120: Dequeue failed\n\tat oracle.jms.AQjmsError.throwEx(AQjmsError.java:336)\n\tat oracle.jms.AQjmsConsumer.jdbcDequeue(AQjmsConsumer.java:1914)\n\tat oracle.jms.AQjmsConsumer.receiveFromAQ(AQjmsConsumer.java:1358)\n\tat oracle.jms.AQjmsConsumer.receiveFromAQ(AQjmsConsumer.java:1278)\n\tat oracle.jms.AQjmsConsumer.receiveFromAQ(AQjmsConsumer.java:1256)\n\tat oracle.jms.AQjmsConsumer.receive(AQjmsConsumer.java:1074)\n\tat io.confluent.connect.jms.core.source.JmsClientHelper.receive(JmsClientHelper.java:218)\n\tat io.confluent.connect.jms.core.source.BaseJmsSourceTask.receive(BaseJmsSourceTask.java:182)\n\t... 14 more\nCaused by: java.sql.SQLException: ORA-25226: dequeue failed, queue RMS.SUPPLIER_QUEUE is not enabled for dequeue\n\n\tat oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)\n\tat oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:392)\n\tat oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:385)\n\tat oracle.jdbc.driver.T4Caqdq.processError(T4Caqdq.java:486)\n\tat oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)\n\tat oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)\n\tat oracle.jdbc.driver.T4Caqdq.doOAQDQ(T4Caqdq.java:178)\n\tat oracle.jdbc.driver.T4CConnection.doDequeue(T4CConnection.java:5035)\n\tat oracle.jdbc.driver.PhysicalConnection.dequeue(PhysicalConnection.java:10132)\n\tat oracle.jdbc.driver.PhysicalConnection.dequeue(PhysicalConnection.java:10184)\n\tat oracle.jms.AQjmsConsumer.jdbcConnectionDequeueCheck25242(AQjmsConsumer.java:2369)\n\tat oracle.jms.AQjmsConsumer.jdbcDequeue(AQjmsConsumer.java:1589)\n\t... 20 more\n

Can someone shed light on this please?

**Comment by andrewegel** [comment]
Seeking support on this connector means you're going to need to go through support@confluent.io's channels as its one of Confluent's Enterprise Connectors - Try emailing to see if theres some support that can be given out. 

But in general this project just builds Docker Images that can happen to install the JMS connector, it is not the code that builds the JMS connector (which is private), so this GitHub repo's issue is not an appropriate place to seek support on this connector's specific issue.
