### ISSUE TITLE
Image cp-kafka-connect:7.0.1 has multiple vulnerabilities

### ISSUE THREAD

**Issue by moyingnana** [confluentinc/kafka-images#154]
We have performed image scan via anchore. The result shows that there are many critical/high vulnerabilities. Could you help to check?

The way of building custom image is recommended here https://docs.confluent.io/home/connect/self-managed/extending.html. 
Image Dockerfile:

FROM  confluentinc/cp-kafka-connect:7.0.1
RUN   confluent-hub install --no-prompt neo4j/kafka-connect-neo4j:2.0.0

Anchore result is attched.

[neo4j-kafka-connector_latest-vuln.json.csv](https://github.com/confluentinc/kafka-images/files/8402242/neo4j-kafka-connector_latest-vuln.json.csv)

**Comment by andrewegel** [comment]
I glanced over your report, and any vulnerabilities discovered under `/usr/share/confluent-hub-components/neo4j-kafka-connect-neo4j` would need to be handled by this team:

https://github.com/neo4j-contrib/neo4j-streams

This software project just builds the docker image - if whats being installed (`neo4j/kafka-connect-neo4j`) at runtime has vulnerabilities, then you have to get those maintainers to update their code's dependencies & have them make a release.
