### ISSUE TITLE
Question: Is there a multi-arch docker image for cp-server:6.2.5 ?

### ISSUE THREAD

**Issue by noorul** [confluentinc/kafka-images#183]
We are using cp-server:6.2.5 image for local development on laptop. We have new employees with M1 Mac. We could not find multi-arch image for cp-server:6.2.5. If available please share the link. If not is there a plan to make this available?

**Comment by andrewegel** [comment]
ARM64 images are only for CP 7.2 and above - You will not see ARM64 images for anything lower.
