### ISSUE TITLE
Prisma compute security vulnerabilities

### ISSUE THREAD

**Issue by zhertig** [confluentinc/kafka-images#263]
We are seeing a number of medium/high/critical vulnerabilities from Prisma Compute scans for the following images:
cp-kafka:latest
cp-schema-registry:7.6.0
cp-zookeeper:latest

For example. The following is a **Critical** issue that applies to all 3:
"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes "e-Tugra" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from "e-Tugra" from the root store."

Wondering if scans are run for these periodically and new versions released. Can we expect newly patched versions of these images in the near future? If you have any dates/schedules for these that would be helpful. Thank you

Also I realize this might not be the correct project for schema-registry, but the [issue tracker](https://github.com/confluentinc/cp-docker-images) referenced by [docker hub for schema-registry](https://hub.docker.com/r/confluentinc/cp-schema-registry) has been archived. If you are aware of a better place to report issues for schema-registry please let me know.

**Comment by janjwerner-confluent** [comment]
@zhertig 
New version of Confluent Platform 7.6.1 has been released. Confluent Platform is released quarterly with the updates. 
please review:
https://support.confluent.io/hc/en-us/articles/13082992005396-Confluent-Security-Advisory-CONFSA-Publication-Policy
