### ISSUE TITLE
Addressing UBI8 Base Image CVEs

### ISSUE THREAD

**Issue by darkmastermindz** [confluentinc/kafka-images#265]
There are lots of CVEs coming from the base ubi8 image not up to date. Would like to address this in an epic.

**Comment by darkmastermindz** [comment]
@andrewegel @ewencp I still see that there's a security update gap mentioned in #51

**Comment by janjwerner-confluent** [comment]
@darkmastermindz 
new version of Confluent Platform container images have been released on dockerhub.
Please update to the latest version.
