### ISSUE TITLE
How to support graceful shutdown of cp-kafka

### ISSUE THREAD

**Issue by cobolbaby** [confluentinc/kafka-images#30]
After the container is killed, a large number of partition directories need to be traversed when the container is rebuilt. 
The process takes a long time. Could the cp-kafka container monitor `container stop signal` and automatically execute command `kafka-server-stop`

Current version: 
- cp-kafka: v5.0.3

**Comment by cobolbaby** [comment]
Just like:

```bash
function sigterm_handler() {
    echo "SIGTERM signal received, try to gracefully shutdown all services..."
    kafka-server-stop
}

trap "sigterm_handler; exit" TERM
```

**Comment by ReasonDuan** [comment]
You can use "docker stop pc-kafka" to graceful shutdown.

**Comment by cobolbaby** [comment]
@ReasonDuan  which version?

**Comment by ReasonDuan** [comment]
> @ReasonDuan which version?

cp-kafka:3.2.0 and cp-kafka:5.2.1

**Comment by cobolbaby** [comment]
It seems that I need to increase the `stop_grace_period` to make it works.
