### ISSUE TITLE
OpenSSL not usable in image "confluentinc/cp-kafka:7.8.0"

### ISSUE THREAD

**Issue by JKollien** [confluentinc/kafka-images#365]
Index digest 
sha256:18042a3a86ba21c1ff9b315ce243aed8bc7fb4794967a83687e4ba1b12283493

It is not possible to execute any `openssl` command, e.g., the following:
```
$ openssl version
openssl: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

Referencing solutions for the issue and looking at the image layers on [dockerhub](https://hub.docker.com/layers/confluentinc/cp-kafka/7.8.0/images/sha256-70a896db5104d8c271306c36a0970d8028b4afc2e840f0cb98a0239899451aed?context=explore), I can see a new command that not existed previously, that might have to do with this (line 59):
```
ENV LD_LIBRARY_PATH=/usr/local/lib:
```

What do you guys think?

**Comment by denyskril** [comment]
Same issue...

**Comment by JKollien** [comment]
ENV was changed to `ENV LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:` solving the issue for us.

Thanks!
