### ISSUE TITLE
Root owned writable files

### ISSUE THREAD

**Issue by lemrouch** [confluentinc/kafka-images#74]
Hi, my security system complains there are files owned by root and writable by anyone in /etc/kafka/.
```
~# docker run -it --rm confluentinc/cp-zookeeper /bin/bash
[appuser@50635fd4475d ~]$ ls -l /etc/kafka/
total 72
-rw-rw-rw- 1 root root  906 Feb  4 16:55 connect-console-sink.properties
-rw-rw-rw- 1 root root  909 Feb  4 16:55 connect-console-source.properties
..
```
Do you think it's good idea to just run `chmod o-w` or `chown appuser.` on them?
I'm not familiar with kafka and I'm not sure if the user needs permissions to alter them.

**Comment by andrewegel** [comment]
This is resolved in https://github.com/confluentinc/kafka-images/pull/116
