### ISSUE TITLE
Release note

### ISSUE THREAD

**Issue by FrancoisPoinsot** [confluentinc/kafka-images#82]
I recently switch the kafka-connect image I use from 5.5.1 to 6.1.1 and noticed a breaking change: the jdbc source connector was not installed by default anymore.
Loves the new tool `confluent-hub` to manage the connectors now. Great change.

Now my question is, is there some release notes somewhere that lists the breaking changes from one major release to another?
Not the release of the kafka application itself. I am talking about the release of the docker images.

**Comment by andrewegel** [comment]
You would find these here: https://docs.confluent.io/platform/current/release-notes/index.html

We have recently published some Docker Image changes, but Docker Images themselves don't get many changes, and the issue you've stumbled on is already documented here: https://docs.confluent.io/platform/6.0.0/release-notes/index.html#connectors

```
Beginning with Confluent Platform 6.0, connectors are no longer packaged natively with Confluent Platform. All formerly packaged connectors must be downloaded directly from Confluent Hub. To clearly delineate this change in distribution, we have bumped versions to 10.0.0. For more information, see Supported Connectors.
```
